# CMake generated Testfile for 
# Source directory: /home/bkessler/Repositories/hatschet
# Build directory: /home/bkessler/Repositories/hatschet
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Read "./hatschet" "--test=READ")
set_tests_properties(Read PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;377;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(Moovac "./hatschet" "--test=MOOVAC")
set_tests_properties(Moovac PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;378;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(ReadWriteReadSchedule "./hatschet" "--test=RWRS")
set_tests_properties(ReadWriteReadSchedule PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;379;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(ModuloSDC "./hatschet" "--test=MODULOSDC")
set_tests_properties(ModuloSDC PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;380;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(API "./hatschet" "--test=API")
set_tests_properties(API PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;381;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(ASAPHC "./hatschet" "--test=ASAPHC")
set_tests_properties(ASAPHC PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;382;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(ALAPHC "./hatschet" "--test=ALAPHC")
set_tests_properties(ALAPHC PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;383;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(ULScheduler "./hatschet" "--test=ULScheduler")
set_tests_properties(ULScheduler PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;384;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(criticalpath "./hatschet" "--test=CRITPATH")
set_tests_properties(criticalpath PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;385;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(KosarajuSCC "./hatschet" "--test=KOSARAJU")
set_tests_properties(KosarajuSCC PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;386;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(CompareMSAlgorithms "./hatschet" "--test=COMPAREMSALGORITHMS")
set_tests_properties(CompareMSAlgorithms PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;387;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(rationalIISchedulerTest "./hatschet" "--test=RATIONALIISCHEDULER")
set_tests_properties(rationalIISchedulerTest PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;388;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(rationalIISchedulerFimmelTest "./hatschet" "--test=RATIONALIISCHEDULERFIMMEL")
set_tests_properties(rationalIISchedulerFimmelTest PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;389;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(ratIIVerifierWrongMRTDetected "./hatschet" "--test=ratIIVerifierWrongMRTDetected")
set_tests_properties(ratIIVerifierWrongMRTDetected PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;390;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(ratIIVerifierWrongCausalityDetected "./hatschet" "--test=ratIIVerifierWrongCausalityDetected")
set_tests_properties(ratIIVerifierWrongCausalityDetected PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;391;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(uniformRatII "./hatschet" "--test=UNIFORMRATIONALIISCHEDULER")
set_tests_properties(uniformRatII PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;393;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(uniformRatIINew "./hatschet" "--test=UNIFORMRATIONALIISCHEDULERNEW")
set_tests_properties(uniformRatIINew PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;394;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(nonUniformRatII "./hatschet" "--test=NONUNIFORMRATIONALIISCHEDULER")
set_tests_properties(nonUniformRatII PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;395;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(ratIIModuloQ "./hatschet" "--test=RATIONALIIMODULOQ")
set_tests_properties(ratIIModuloQ PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;396;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(ratIISCCQ "./hatschet" "--test=RATIONALIISCCQ")
set_tests_properties(ratIISCCQ PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;397;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(ratIIUnroll "./hatschet" "--test=UNROLLSCHEDULER")
set_tests_properties(ratIIUnroll PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;398;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(integerIINonRect "./hatschet" "--test=INTEGERIINONRECT")
set_tests_properties(integerIINonRect PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;399;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(optimalBinding "./hatschet" "--test=ILPBASEDINTIIBINDING")
set_tests_properties(optimalBinding PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;400;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(treeBind "./hatschet" "--test=TREEBIND")
set_tests_properties(treeBind PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;401;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(treeBindCommutative "./hatschet" "--test=TREEBINDCOMMUTATIVE")
set_tests_properties(treeBindCommutative PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;402;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(congBind "./hatschet" "--test=ILPBASEDINTIIBINDINGCONG")
set_tests_properties(congBind PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;403;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(CaDiCaL "./hatschet" "--test=CADICAL")
set_tests_properties(CaDiCaL PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;407;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
add_test(Z3 "./hatschet" "--test=Z3")
set_tests_properties(Z3 PROPERTIES  _BACKTRACE_TRIPLES "/home/bkessler/Repositories/hatschet/CMakeLists.txt;411;add_test;/home/bkessler/Repositories/hatschet/CMakeLists.txt;0;")
